@echo off
for %%I in ("%~dp0..") do set "ICML_PROJECT=%%~fI"
set "CODEX_HOME=%USERPROFILE%\.codex"
set "CODEX_SQLITE_HOME="
set "TEMP=%ICML_PROJECT%\cache\tmp"
set "TMP=%TEMP%"
set "PIP_CACHE_DIR=%ICML_PROJECT%\cache\pip"
set "PYTHONUTF8=1"
set "PYTHONIOENCODING=utf-8"
set "PYTHONDONTWRITEBYTECODE=1"
set "PIP_DISABLE_PIP_VERSION_CHECK=1"
set "PATH=%ICML_PROJECT%\.venv\Scripts;%ICML_PROJECT%\.tools\git\cmd;%ICML_PROJECT%\.tools\codex;%PATH%"
set "PYTHONHOME="
set "PYTHONPATH="
set "OPENAI_API_KEY="
set "CODEX_API_KEY="
set "CODEX_ACCESS_TOKEN="
cd /d "%ICML_PROJECT%"
